import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import "../globals.css";
import TopBar from "@/components/shared/TopBar";
import BottomBar from "@/components/shared/BottomBar";
import LeftSidebar from "@/components/shared/LeftSidebar";
import RightSidebar from "@/components/shared/RightSidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inter.className}
      >
        <TopBar />
          <main>
            <LeftSidebar/>
              <section className="main-container">
                <div className="w-full max-w-4xl">
                    {children}
                </div>

              </section>
            <RightSidebar/>
          </main>



        <BottomBar/>
      </body>
    </html>
  );
}
